# Generated by Django 4.0.4 on 2022-04-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/products/categories/', verbose_name='Изображение'),
        ),
    ]
