# Generated by Django 4.0.4 on 2023-03-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_composition_invoice_invoicetable_compositiontable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicetable',
            name='docptr',
        ),
        migrations.RemoveField(
            model_name='invoicetable',
            name='mt',
        ),
        migrations.RemoveField(
            model_name='invoicetable',
            name='product',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceTable',
        ),
    ]
