# Generated by Django 3.2.6 on 2021-08-08 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('phone2', models.CharField(max_length=20, verbose_name='Телефон2')),
                ('messenger', models.CharField(choices=[('SM', 'SMS'), ('WA', 'WhatsApp'), ('VB', 'Viber'), ('TG', 'Telegram'), ('VK', 'VKontakte'), ('FB', 'Facebook'), ('WC', 'WeChat'), ('SC', 'Snapchat'), ('SK', 'Skype')], default='SM', max_length=2, verbose_name='Мессенджер')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('isActive', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
