# Generated by Django 4.0 on 2022-04-20 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contacts', '0007_alter_contact_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to='auth.user', verbose_name='Автор'),
        ),
    ]
