# Generated by Django 4.0.4 on 2023-03-22 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measure', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_remove_invoicetable_docptr_remove_invoicetable_mt_and_more'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docNum', models.CharField(max_length=16, verbose_name='Номер')),
                ('docDate', models.DateTimeField(verbose_name='Дата')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('isActive', models.BooleanField(default=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.stores', verbose_name='Склад')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Накладная',
                'verbose_name_plural': 'Накладные',
            },
        ),
        migrations.CreateModel(
            name='InvoiceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Количество')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('docptr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice', verbose_name='Накладная')),
                ('mt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='measure.measure', verbose_name='ед. изм.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Накладная ТЧ',
                'verbose_name_plural': 'Накладная ТЧ',
            },
        ),
    ]
