# Generated by Django 4.0.4 on 2023-03-23 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_invoicetable_docptr_remove_invoicetable_mt_and_more'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetable',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.products', verbose_name='Товар'),
        ),
    ]
