# Generated by Django 4.0.4 on 2022-09-17 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.suppliergroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Группа поставщиков',
                'verbose_name_plural': 'Группы поставщиков',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Наименование')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='Телефон2')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('post_address', models.TextField(blank=True, verbose_name='Почтовый адрес')),
                ('INN', models.CharField(max_length=12, verbose_name='ИНН')),
                ('KPP', models.CharField(max_length=9, verbose_name='КПП')),
                ('director', models.CharField(max_length=128, verbose_name='Руководитель')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('isActive', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.suppliergroup', verbose_name='Группа')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщик',
            },
        ),
    ]
